server:
  port: 8081
spring:
  application:
    name: member
  rabbitmq:
    host: 127.0.0.1
    port: 5672 # 시스템은 5672로 등록
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,busrefresh